######## FILE TEMPLATES ########

AIS_template = {
    "parameter": [
        "[SINGLE ABSOLUTE IRRADIANCE MEASUREMENT]",
        "author",
        "date_time",
        "[PROJECT]",
        "project_id",        
        "PL",
        "ML,"
        "aanvraagdatum",
        "uiterste_datum",
        "[LAMP]",
        "institution",
        "lamp",
        "option",
        "lamp_fiber",
        "lamp_filter",
        "distance_mm",
        "[DEVICE]",
        "device",
        "sensor_type",
        "sensor_area_m2",
        "[ANALYSIS]",
        "Id",
        "integration_time_ms",
        "average",
        "boxcar",
        "measurements_N",
        "CIE",
        "[ENERGY DATA]",
        "illuminance_lux",
        "luminous-flux_mlm",
        "irradiance_W/m2",
        "power_mW",
        "luminous-efficacy-ratio_lm/W",
        "CCT_K",
        "[MEASUREMENT DATA]",
        "wavelength_nm",
    ]
}

RS_template = {
    "parameter": [
        "[SINGLE REFLECTANCE MEASUREMENT]",
        "author",
        "date_time",
        "[PROJECT]",
        "project_id",        
        "PL",
        "ML",
        "aanvraagdatum",
        "uiterste_datum",
        "comments",
        "[OBJECT]",
        "institution",
        "object_id",
        "object_category",
        "object_type",
        "object_technique",        
        "object_title",
        "object_creator",
        "object_date",      
        "object_support",        
        "[DEVICE]",
        "system",
        "device",
        "geometry",
        "option",
        "lamp",
        "filter",
        "distance_coll_mm",
        "distance_cam_mm",
        "fiber_ill",
        "fiber_coll",
        "white_ref",
        "specular_component",        
        "integration_time_ms",
        "average",
        "measurement_area",
        "boxcar_width",
        "[ANALYSIS]",
        "Id",
        "group",  
        "color",     
        "colorants",
        "colorant_names",
        "ratio",
        "binding",
        "thickness_microns",
        "background",
        "measurements_N",
        "[COLORIMETRIC DATA]",
        "observer",
        "illuminant",
        "x",
        "y",
        "L*",
        "a*",
        "b*",
        "C*",
        "h",
        "[MEASUREMENT DATA]",
        "wavelength_nm",
    ]
}

TS_template = {
    "parameter": [
        "[SINGLE TRANSMISSION MEASUREMENT]",
        "authors",
        "date_time",
        "project_id",
        "[SAMPLE DATA]",
        "sample_type",
        "sample_nb",
        "name",
        "pigment",
        "binding",
        "colour",
        "ratio",
        "thickness_microns",
        "sample_support",
        "sample_date",
        "comments",
        "[LAMP DATA]",
        "lamp",
        "option",
        "lamp_fiber",
        "lamp_filter",
        "distance_mm",
        "[DEVICE DATA]",
        "device",
        "sensor_type",
        "sensor_area_m2",
        "[ANALYSIS DATA]",
        "Id",
        "group",
        "integration_time_ms",
        "average",
        "boxcar",
        "measurements_N",  
        "[MEASUREMENT DATA]",
        "wavelength_nm",
    ]
}

RIS_template = {
    "parameter": [
        "[SINGLE RELATIVE IRRADIANCE MEASUREMENT]",
        "author",
        "date_time",
        "project_id",
        "[LAMP DATA]",
        "lamp",
        "option",
        "lamp_fiber",
        "lamp_filter",
        "distance_mm",
        "[DEVICE DATA]",
        "device",
        "sensor_type",
        "sensor_area_m2",
        "[ANALYSIS DATA]",
        "Id",
        "integration_time_ms",
        "average",
        "boxcar",
        "measurements_N",    
        "[MEASUREMENT DATA]",
        "wavelength_nm",
    ]
}

BS_INFO_template = {
    "parameter": [
        "[BEAM SPOT ASSESSMENT]",
        "author",
        "date",
        "project_id",
        "[IMAGE DATA]",
        "nb",
        "support",
        "gain",
        "exposure_ms",
        "camera",
        "position",        
        "resolution_micron/pixel",
        "MFT",
        "[MFT DEVICE DATA]",
        "lamp",
        "mode",
        "zoom",
        "iris",
        "filter",
        'distance_camera_mm',
        "distance_ill_mm",
        "fiber_ill",
        "[BEAM SPOT DATA]",
        "FW10M_micron",
        "FW20M_micron",
        "FWHM_micron",
        "FW80M_micron",
        "power_mW",
        "ill_FW10M_lux",
        "ill_FW20M_lux",  
        "ill_FW40M_lux",        
        "ill_FWHM_lux",
        "ill_FW80M_lux",
        "irr_FW10M_W/m2",
        "irr_FW20M_W/m2", 
        "irr_FW40M_W/m2",    
        "irr_FWHM_W/m2",
        "irr_FW80M_W/m2",
    ]
}

MFT_INFO_template = {
    "parameter": [
        "[SINGLE MICRO-FADING ANALYSIS]",
        "author",
        "date_time",
        "[PROJECT DATA]",
        "project_id",
        "PL",
        "ML",
        "aanvraagdatum",
        "uiterste_datum",
        "comment",        
        "[OBJECT DATA]",
        "institution",
        "object_id",
        "object_category",
        "object_type",
        "object_technique",
        "object_title",
        "object_creator",
        "object_date",
        "object_support",
        "color",
        "colorants",
        "colorants_name",
        "binding",
        "ratio",        
        "thickness_microns",
        "status",
        "[DEVICE DATA]",
        "device",
        "measurement_mode",
        "zoom",
        "iris",
        "geometry",
        "distance_ill_mm",
        "distance_coll_mm",
        "fiber_fading",
        "fiber_ill",
        "fiber_coll",
        "lamp_fading",
        "lamp_ill",
        "filter_fading",
        "filter_ill",
        "white_ref",
        "[ANALYSIS DATA]",
        "meas_id",
        "group",
        "group_description",
        "background",
        "specular_component",
        "integration_time_ms",
        "average",
        "duration_min",
        "interval_sec",
        "measurements_N",
        "illuminant",
        "observer",
        "[BEAM DATA]",
        "beam_photo",
        "resolution_micron/pixel",
        "FWHM_micron",
        "power_mW",
        "irradiance_W/m**2",
        "luminuous_flux_lm",
        "illuminance_lux",
        "[RESULTS]",
        "total_dose_MJ/m**2",
        "total_dose_klxh",
        "fitted_dE00_eq",
        "fitted_dE00_rate_@_10Mlxh",
        "fitted_dE00_rate_@_20MJ/m**2",
        "dE00_@_300klxh",
        "dE00_@_3MJ/m**2",        
        "dEab_final",
        "dE00_final",
        "dR_VIS_final",
    ]
}

Power_template = {
    "parameter": [
        "[SINGLE RADIANT POWER MEASUREMENT]",
        "author",
        "date_time",
        "[PROJECT]",
        "project_Id",        
        "PL",
        "ML",
        "aanvraagdatum",
        "uiterste_datum",
        "comments",
        "[LAMP DATA]",
        "lamp",
        "option",
        "zoom",
        "iris",
        "lamp_fiber",
        "lamp_filter",
        "distance_mm",
        "[DEVICE DATA]",
        "device",
        "sensor_type",
        "sensor_area_m2",
        "[ANALYSIS DATA]",
        "Id",
        "group",
        "duration_min",
        "interval_sec",
        "measurements_N",
        "[STATS]",
        "mean_power_mW",
        "std_power_mW",
        "[MEASUREMENT DATA]",
        "time_sec",
    ]
}
